name: Publish NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build library
        run: |
          npm install
          npm run nx run ngx-fluent-buttons:build:production

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        working-directory: dist/libs/ngx-fluent-buttons
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
